import type { Metadata } from "next";
import "./globals.css";
import "./fonts.css";
import "../fonts/MessinaSans.css";
import "../fonts/montserrat.css";

export const metadata: Metadata = {
  title: "Twinning labs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
